/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qdbm_VillaCursor */

#ifndef _Included_qdbm_VillaCursor
#define _Included_qdbm_VillaCursor
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: class_00024qdbm_00024ADBM */
/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurecode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_qdbm_VillaCursor_vlmulcurecode
  (JNIEnv *, jclass);

/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurnew
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_VillaCursor_vlmulcurnew
  (JNIEnv *, jobject, jint);

/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurdelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_qdbm_VillaCursor_vlmulcurdelete
  (JNIEnv *, jobject);

/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurfirst
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_VillaCursor_vlmulcurfirst
  (JNIEnv *, jobject, jint);

/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurlast
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_VillaCursor_vlmulcurlast
  (JNIEnv *, jobject, jint);

/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurprev
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_VillaCursor_vlmulcurprev
  (JNIEnv *, jobject, jint);

/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurnext
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_VillaCursor_vlmulcurnext
  (JNIEnv *, jobject, jint);

/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurjump
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_qdbm_VillaCursor_vlmulcurjump
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurkey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_qdbm_VillaCursor_vlmulcurkey
  (JNIEnv *, jobject, jint);

/*
 * Class:     qdbm_VillaCursor
 * Method:    vlmulcurval
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_qdbm_VillaCursor_vlmulcurval
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
