/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qdbm_Villa */

#ifndef _Included_qdbm_Villa
#define _Included_qdbm_Villa
#ifdef __cplusplus
extern "C" {
#endif
#undef qdbm_Villa_ENOERR
#define qdbm_Villa_ENOERR 0L
#undef qdbm_Villa_EFATAL
#define qdbm_Villa_EFATAL 1L
#undef qdbm_Villa_EMODE
#define qdbm_Villa_EMODE 2L
#undef qdbm_Villa_EBROKEN
#define qdbm_Villa_EBROKEN 3L
#undef qdbm_Villa_EKEEP
#define qdbm_Villa_EKEEP 4L
#undef qdbm_Villa_ENOITEM
#define qdbm_Villa_ENOITEM 5L
#undef qdbm_Villa_EALLOC
#define qdbm_Villa_EALLOC 6L
#undef qdbm_Villa_EMAP
#define qdbm_Villa_EMAP 7L
#undef qdbm_Villa_EOPEN
#define qdbm_Villa_EOPEN 8L
#undef qdbm_Villa_ECLOSE
#define qdbm_Villa_ECLOSE 9L
#undef qdbm_Villa_ETRUNC
#define qdbm_Villa_ETRUNC 10L
#undef qdbm_Villa_ESYNC
#define qdbm_Villa_ESYNC 11L
#undef qdbm_Villa_ESTAT
#define qdbm_Villa_ESTAT 12L
#undef qdbm_Villa_ESEEK
#define qdbm_Villa_ESEEK 13L
#undef qdbm_Villa_EREAD
#define qdbm_Villa_EREAD 14L
#undef qdbm_Villa_EWRITE
#define qdbm_Villa_EWRITE 15L
#undef qdbm_Villa_ELOCK
#define qdbm_Villa_ELOCK 16L
#undef qdbm_Villa_EUNLINK
#define qdbm_Villa_EUNLINK 17L
#undef qdbm_Villa_EMKDIR
#define qdbm_Villa_EMKDIR 18L
#undef qdbm_Villa_ERMDIR
#define qdbm_Villa_ERMDIR 19L
#undef qdbm_Villa_EMISC
#define qdbm_Villa_EMISC 20L
#undef qdbm_Villa_OREADER
#define qdbm_Villa_OREADER 1L
#undef qdbm_Villa_OWRITER
#define qdbm_Villa_OWRITER 2L
#undef qdbm_Villa_OCREAT
#define qdbm_Villa_OCREAT 4L
#undef qdbm_Villa_OTRUNC
#define qdbm_Villa_OTRUNC 8L
#undef qdbm_Villa_ONOLCK
#define qdbm_Villa_ONOLCK 16L
#undef qdbm_Villa_OLCKNB
#define qdbm_Villa_OLCKNB 32L
#undef qdbm_Villa_OZCOMP
#define qdbm_Villa_OZCOMP 64L
#undef qdbm_Villa_OYCOMP
#define qdbm_Villa_OYCOMP 128L
#undef qdbm_Villa_OXCOMP
#define qdbm_Villa_OXCOMP 256L
#undef qdbm_Villa_CMPLEX
#define qdbm_Villa_CMPLEX 0L
#undef qdbm_Villa_CMPNUM
#define qdbm_Villa_CMPNUM 1L
#undef qdbm_Villa_CMPDEC
#define qdbm_Villa_CMPDEC 2L
#undef qdbm_Villa_CMPOBJ
#define qdbm_Villa_CMPOBJ 3L
#undef qdbm_Villa_DOVER
#define qdbm_Villa_DOVER 0L
#undef qdbm_Villa_DKEEP
#define qdbm_Villa_DKEEP 1L
#undef qdbm_Villa_DCAT
#define qdbm_Villa_DCAT 2L
#undef qdbm_Villa_DDUP
#define qdbm_Villa_DDUP 3L
#undef qdbm_Villa_DDUPR
#define qdbm_Villa_DDUPR 4L
#undef qdbm_Villa_JFORWARD
#define qdbm_Villa_JFORWARD 0L
#undef qdbm_Villa_JBACKWARD
#define qdbm_Villa_JBACKWARD 1L
#undef qdbm_Villa_CPCURRENT
#define qdbm_Villa_CPCURRENT 0L
#undef qdbm_Villa_CPBEFORE
#define qdbm_Villa_CPBEFORE 1L
#undef qdbm_Villa_CPAFTER
#define qdbm_Villa_CPAFTER 2L
/* Inaccessible static: class_00024qdbm_00024ADBM */
/*
 * Class:     qdbm_Villa
 * Method:    vlinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_qdbm_Villa_vlinit
  (JNIEnv *, jclass);

/*
 * Class:     qdbm_Villa
 * Method:    vlversion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_qdbm_Villa_vlversion
  (JNIEnv *, jclass);

/*
 * Class:     qdbm_Villa
 * Method:    vlecode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlecode
  (JNIEnv *, jclass);

/*
 * Class:     qdbm_Villa
 * Method:    vlerrmsg
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_qdbm_Villa_vlerrmsg
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlopen
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlopen
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlclose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlclose
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlput
 * Signature: (I[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlput
  (JNIEnv *, jclass, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlout
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlout
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlget
 * Signature: (I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_qdbm_Villa_vlget
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlvsiz
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlvsiz
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlvnum
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlvnum
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlcurfirst
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlcurfirst
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlcurlast
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlcurlast
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlcurprev
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlcurprev
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlcurnext
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlcurnext
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlcurjump
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlcurjump
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlcurkey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_qdbm_Villa_vlcurkey
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlcurval
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_qdbm_Villa_vlcurval
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlcurput
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlcurput
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlcurout
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlcurout
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlsettuning
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_qdbm_Villa_vlsettuning
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlsync
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlsync
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vloptimize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vloptimize
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlname
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_qdbm_Villa_vlname
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlfsiz
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlfsiz
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vllnum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vllnum
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlnnum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlnnum
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlrnum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlrnum
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlwritable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlwritable
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlfatalerror
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlfatalerror
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlinode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlinode
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlmtime
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_qdbm_Villa_vlmtime
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vltranbegin
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vltranbegin
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vltrancommit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vltrancommit
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vltranabort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vltranabort
  (JNIEnv *, jclass, jint);

/*
 * Class:     qdbm_Villa
 * Method:    vlremove
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_qdbm_Villa_vlremove
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
