#!/bin/sh
PATH=/bin:/usr/bin:
#
#	Convert from arbitrary format to MUSH V2 GDBM format.
#
case $# in
	1)	./dbconvert $1 Cw >/dev/null 2>&1 ;;
	2)	./dbconvert $1 Cw <$2 >/dev/null 2>&1 ;;
	3)	./dbconvert $1 Cw <$2 >/dev/null 2>$3 ;;
	*)	echo Usage: $0 'gdbm_file [source_file [log_file]]'; exit 1 ;;
esac

exit 0
