#!/bin/sh
PATH=/bin:/usr/bin:
#
#	Convert from arbitrary format to MUSH V2 flat file format.
#
case $# in
	1)	./dbconvert $1 x ;;
	2)	./dbconvert $1 x <$2 ;;
	3)	./dbconvert $1 x <$2 >$3 ;;
	*)	echo Usage: $0 'gdbm_file [source_file [dest_file]]'; exit 1 ;;
esac

exit 0
