.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DPMGR 1 "2005-05-23" "Man Page" "Quick Database Manager"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dpmgr \- administration utility for QDBM Depot
.SH SYNOPSIS
.B dpmgr create
.RI "[-s] [-bnum " num "] " name
.br
.B dpmgr put
.RI "[-kx|-ki] [-vx|-vi|-vf] [-keep|-cat] [-na] " name " " key " " val
.br
.B dpmgr out
.RI "[-kx|-ki] " name " " key
.br
.B dpmgr get
.RI "[-nl] [-kx|-ki] [-start " num "] [-max " num "] [-ox] [-n] " name " " key
.br
.B dpmgr list
.RI "[-nl] [-k|-v] [-ox] " name
.br
.B dpmgr optimize
.RI "[-bnum " num "] [-na] " name
.br
.B dpmgr inform
.RI "[-nl] " name
.br
.B dpmgr remove
.I name
.br
.B dpmgr repair
.I name
.br
.B dpmgr exportdb
.I name file
.br
.B dpmgr importdb
.I name file
.br
.B dpmgr snaffle
.RI "[-kx|-ki] [-ox] [-n] " name " " key
.br
.B dpmgr version
.SH DESCRIPTION
This manual page documents briefly the
.B dpmgr
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBdpmgr\fP is a utility for debugging Depot and its applications. It
features editing and checking of a database. It can be used for database
applications with shell scripts. This command is used in the above format.
\fIname\fP specifies a database name.
\fIkey\fP specifies the key of a record. \fIval\fP
specifies the value of a record.
.SH OPTIONS
A summary of options is included below.
For a complete description, see the
file:///usr/share/doc/qdbm-doc/spex.html#depotcli.
.TP
.B \-s
make the file sparse.
.TP
.BI "\-bnum " num
specify the number of the elements of the bucket array.
.TP
.B \-kx
treat \fIkey\fP as a binary expression of hexadecimal notation.
.TP
.B \-ki
treat \fIkey\fP as an integer expression of decimal notation.
.TP
.B \-vx
treat \fIval\fP as a binary expression of hexadecimal notation.
.TP
.B \-vi
treat \fIval\fP as an integer expression of decimal notation.
.TP
.B \-vf
read the value from a file specified with \fIval\fP.
.TP
.B \-keep
specify the storing mode for `DP_DKEEP'.
.TP
.B \-cat
specify the storing mode for `DP_DCAT'.
.TP
.B \-na
do not set alignment.
.TP
.B \-nl
open the database without file locking.
.TP
.B \-start
specify the beginning offset of a value to fetch.
.TP
.B \-max
specify the max size of a value to fetch.
.TP
.B \-ox
treat the output as a binary expression of hexadecimal notation.
.TP
.B \-n
do not output the tailing newline.
.TP
.B \-k
output keys only.
.TP
.B \-v
output values only.
.SH SEE ALSO
.BR qdbm (3),
.BR dptsv (1),
.BR dpopen (3).
.SH AUTHOR
QDBM was written by Mikio Hirabayashi <mikio@fallabs.com>.
.PP
This manual page was written by Fumitoshi UKAI <ukai@debian.or.jp>,
for the Debian project (but may be used by others).
