.TH QMTTEST 1 "2006-08-10" "Man Page" "Quick Database Manager"
.SH NAME
qmttest \- test cases for thread-safety
.SH SYNOPSIS
.B qmttest
.I name rnum tnum
.SH DESCRIPTION
This manual page documents briefly the
.B qmttest
commands.
.PP
The command \fBqmttest\fP is utility for facility test of thread-safety.
\fIname\fP specifies the prefix of databases.  \fIrnum\fP specifies
the number of records.  \fItnum\fP specifies the number of threads.
.SH SEE ALSO
.BR qdbm (3)
.SH AUTHOR
QDBM was written by Mikio Hirabayashi <mikio@fallabs.com>.
